exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("vendorsinfo")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("vendorsinfo").insert([
        {
          vendorid: 1,
          bussname: "The Beach Chip Truck",
          operatorname: "Billy Bob",
          foodcat: "Fries",
          addnum: "590",
          streetname: "Liverpool",
          streettype: "Road",
          city: "Pickering",
          province: "Ontario",
          password: "password",
          username: "username",
        },
        {
          vendorid: 2,
          bussname: "Chewies Grill",
          operatorname: "Fancy Nancy",
          foodcat: "Greek",
          addnum: "980",
          streetname: "Brock",
          streettype: "Road",
          city: "Pickering",
          province: "Ontario",
          password: "password",
          username: "username",
        },
        {
          vendorid: 3,
          bussname: "Fantastic Funnel Cakes",
          operatorname: "Martha Stewart",
          foodcat: "Dessert",
          addnum: "1814",
          streetname: "Eastbank",
          streettype: "Road",
          city: "Pickering",
          province: "Ontario",
          password: "password",
          username: "username",
        },
        {
          vendorid: 4,
          bussname: "Softie Inc",
          operatorname: "Sally Gal",
          foodcat: "Ice Cream",
          addnum: "24",
          streetname: "Southampton",
          streettype: "Drive",
          city: "Scarborough",
          province: "Ontario",
          password: "password",
          username: "username",
        },
        {
          vendorid: 5,
          bussname: "Pemento Jerk Food Truck",
          operatorname: "Robby Bobby",
          foodcat: "Jamacian",
          addnum: "570",
          streetname: "Kingston",
          streettype: "Road",
          city: "Pickerkng",
          province: "Ontario",
          password: "password",
          username: "username",
        },
        {
          vendorid: 6,
          bussname: "Sals Treat Mobile",
          operatorname: "Sal John",
          foodcat: "Icecream",
          addnum: "155",
          streetname: "Antibes",
          streettype: "Dr",
          city: "Toronto",
          province: "Ontario",
          password: "password",
          username: "username",
        },
      ]);
    });
};
